### Importing Libraries

In [406]:
from IPython.display import display, Markdown
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, FunctionTransformer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.model_selection import cross_val_score
import datetime
import warnings
import pickle
warnings.filterwarnings("ignore")
%matplotlib inline

### Loading Data

In [407]:
df = pd.read_csv('D:/Projects/WineQuality/WineQualityE2E/data/raw/HousePrice.csv')
df.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-02 00:00:00,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
1,2014-05-02 00:00:00,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA
2,2014-05-02 00:00:00,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA
3,2014-05-02 00:00:00,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA
4,2014-05-02 00:00:00,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA

In [408]:
display(Markdown(f"### 📐 Shape"))
display(df.shape)
display(Markdown("### ℹ️ Info"))
df.info()
display(Markdown("### 📊 Descriptive Statistics"))
display(df.describe())
display(Markdown("### 🚫 Null Values"))
display(df.isnull().sum())
display(Markdown("### Total zero values in each column"))
display((df == 0).sum())

### 📐 Shape

(4600, 18)

### ℹ️ Info

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           4600 non-null   object
 1   price          4600 non-null   float64
 2   bedrooms       4600 non-null   float64
 3   bathrooms      4600 non-null   float64
 4   sqft_living    4600 non-null   int64
 5   sqft_lot       4600 non-null   int64
 6   floors         4600 non-null   float64
 7   waterfront     4600 non-null   int64
 8   view           4600 non-null   int64
 9   condition      4600 non-null   int64
 10  sqft_above     4600 non-null   int64
 11  sqft_basement  4600 non-null   int64
 12  yr_built       4600 non-null   int64
 13  yr_renovated   4600 non-null   int64
 14  street         4600 non-null   object
 15  city           4600 non-null   object
 16  statezip       4600 non-null   object
 17  country        4600 non-null   object
dtypes: float64(4), int64(9), object(5)
memory usage: 647.0+ KB

### 📊 Descriptive Statistics

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated
count,4.600000e+03,4600.000000,4600.000000,4600.000000,4.600000e+03,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000
mean,5.519630e+05,3.400870,2.160815,2139.346957,1.485252e+04,1.512065,0.007174,0.240652,3.451739,1827.265435,312.081522,1970.786304,808.608261
std,5.638347e+05,0.908848,0.783781,963.206916,3.588444e+04,0.538288,0.084404,0.778405,0.677230,862.168977,464.137228,29.731848,979.414536
min,0.000000e+00,0.000000,0.000000,370.000000,6.380000e+02,1.000000,0.000000,0.000000,1.000000,370.000000,0.000000,1900.000000,0.000000
25%,3.228750e+05,3.000000,1.750000,1460.000000,5.000750e+03,1.000000,0.000000,0.000000,3.000000,1190.000000,0.000000,1951.000000,0.000000
50%,4.609435e+05,3.000000,2.250000,1980.000000,7.683000e+03,1.500000,0.000000,0.000000,3.000000,1590.000000,0.000000,1976.000000,0.000000
75%,6.549625e+05,4.000000,2.500000,2620.000000,1.100125e+04,2.000000,0.000000,0.000000,4.000000,2300.000000,610.000000,1997.000000,1999.000000
max,2.659000e+07,9.000000,8.000000,13540.000000,1.074218e+06,3.500000,1.000000,4.000000,5.000000,9410.000000,4820.000000,2014.000000,2014.000000

### 🚫 Null Values

date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
street           0
city             0
statezip         0
country          0
dtype: int64

### Total zero values in each column

date                0
price              49
bedrooms            2
bathrooms           2
sqft_living         0
sqft_lot            0
floors              0
waterfront       4567
view             4140
condition           0
sqft_above          0
sqft_basement    2745
yr_built            0
yr_renovated     2735
street              0
city                0
statezip            0
country             0
dtype: int64

### Checking Skewness

In [409]:
df.select_dtypes(include='number').skew()

price            24.790933
bedrooms          0.456447
bathrooms         0.616033
sqft_living       1.723513
sqft_lot         11.307139
floors            0.551441
waterfront       11.682901
view              3.341586
condition         0.959068
sqft_above        1.494211
sqft_basement     1.642732
yr_built         -0.502155
yr_renovated      0.385919
dtype: float64

### Changing Date format and extracting requird features from it

In [410]:
df['date'] = pd.to_datetime(df['date'])
df['SaleYear'] = df['date'].dt.year
df['SaleMonth'] = df['date'].dt.month
df['HouseAge'] = df['SaleYear'] - df['yr_built']
df['Renovated'] = (df['yr_renovated']>0).astype(int)

### Extracting more features

In [411]:
df['Waterfront'] = (df['waterfront']>0).astype(int)

In [412]:
df = df.drop(columns=['date', 'waterfront', 'street', 'statezip', 'country', 'yr_built', 'yr_renovated'])

In [413]:
df = df[df['price']>0]

In [414]:
# Applying Log transform on Price
transform = FunctionTransformer(np.log1p, feature_names_out='one-to-one')
df['price'] = transform.transform(df['price'])

### Train Test Split

In [415]:
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['price']), df['price'], test_size=0.2, random_state=42)

### Model Training

In [416]:
preprocessor = ColumnTransformer(
    transformers=[
        ('Scaling', StandardScaler(), [
                            'bedrooms','bathrooms','sqft_living','sqft_lot',
                            'floors','sqft_above','sqft_basement',
                            'HouseAge','SaleYear']),
        ('Encoding', OrdinalEncoder(categories =[[1,2,3,4,5],[0,1,2,3,4]]), ['condition', 'view']),
        ("Cat", OneHotEncoder(handle_unknown='ignore', sparse_output=False ), ['city']),
        ('bin', 'passthrough', ['Waterfront', 'Renovated'])
    ]
)

In [417]:
pipeline = Pipeline(steps=[
    ('Preprocessing', preprocessor),
    ('ModelTraining', LinearRegression())
])

### Predicting

In [418]:
pipeline.fit(X_train, y_train)
y_pred = pipeline.predict(X_test)

In [419]:
r2 = r2_score(y_test, y_pred)
r2

0.6676933611518383

In [420]:
cross_val_scores = cross_val_score(pipeline, X_train, y_train, cv=10, scoring='r2')

In [421]:
cross_val_scores.mean()

0.7181817089862718